#!/bin/sh
# -*- mode: sh -*-

WWINE_DIR="$HOME/.wwine"
WWINE_ENV_FILE='wwine.env'
WWINE_DEFAULT_ARCH=win64

_wwine_prefix()
{
    _wwine_prefix__name="$1"
    [ -z "$_wwine_prefix__name" ] && return 1
    _wwine_prefix="$WWINE_DIR/$1"
}

_wwine_env_do()
{
    _wwine_env_do__name="$1"
    _wwine_prefix "$1" || return 1
    shift

    (
        [ -r "$_wwine_prefix/$WWINE_ENV_FILE" ] && . "$_wwine_prefix/$WWINE_ENV_FILE"
        export WINEPREFIX="$_wwine_prefix"
        "$@"
    )
}

_wwine_dump_env()
{
    _wwine_dump_env__arch=${2:-$WWINE_DEFAULT_ARCH}
    _wwine_dump_env__arch_short="${_wwine_dump_env__arch#win}"

    cat <<EOF > "$1/$WWINE_ENV_FILE"
export WINESERVER=/usr/lib/wine/wineserver$_wwine_dump_env__arch_short
export WINEARCH=$_wwine_dump_env__arch
EOF
}

_wwine_list()
(
    cd "$WWINE_DIR" 2>/dev/null || return 1
    for _wwine_list__i in *; do
        _wwine_show "$_wwine_list__i"
    done
)

_wwine_show()
(
    cd "$WWINE_DIR/$1" 2>/dev/null || return 1
    echo "$1 : $PWD"
    [ -r "$WWINE_ENV_FILE" ] || return 0
    while read line; do
        printf "  %s\n" "$line"
    done < "$WWINE_ENV_FILE"
)

_wwine_setup()
{
    _wwine_prefix "$1" || return 1
    if [ -d "$_wwine_prefix" ]; then
        _wwine_destroy "$1"
    fi

    mkdir -p "$_wwine_prefix" || return 1

    _wwine_setup__arch="${2:-$WWINE_DEFAULT_ARCH}"
    _wwine_setup__arch_short="${_wwine_setup__arch#win}"

    WINEPREFIX="$_wwine_prefix" WINEARCH="$_wwine_setup__arch" WINESERVER=/usr/lib/wine/wineserver$_wwine_setup__arch_short winecfg
    _wwine_dump_env "$_wwine_prefix" "$_wwine_setup__arch"
}

_wwine_destroy()
(
    _wwine_prefix "$1" || return 1
    rm -Rf "$_wwine_prefix"
)

_wwine_exe_resolve()
{
    _wwine_exe_resolve=$(find "$1" -name "$2")
    [ -z "$_wwine_exe_resolve" ] && return 1
    return 0
}

_wwine_exe()
{
    _wwine_prefix "$1" || return 1
    shift

    _wwine_exe__cmd="$1"
    shift

    if [ ! -r "$_wwine_exe__cmd" ]; then
        if _wwine_exe_resolve "$_wwine_prefix" "$_wwine_exe__cmd"; then
            _wwine_exe__cmd="$_wwine_exe_resolve"
        fi
    fi

    _wwine_env_do "$_wwine_prefix__name" wine "$_wwine_exe__cmd" "$@"
}

_wwine_tricks()
{
    _wwine_prefix "$1" || return 1
    shift

    _wwine_env_do "$_wwine_prefix__name" winetricks "$@"
}

_wwine()
{
    _wwine=
    case "$1" in
        ""|l|list) _wwine_list "$@" ;;
        *) _wwine__name="$1" ; shift
           _wwine_prefix "$_wwine__name" || return 1
           _wwine__action="$1"
           [ $# -ne 0 ] && shift
           case "$_wwine__action" in
               ""|l|list|s|show)
                   _wwine_show "$_wwine__name" ;;
               c|create|i|install|setup)
                   _wwine_setup "$_wwine__name" "$@";;
               d|delete|destroy)
                   _wwine_destroy "$_wwine__name" ;;
               e|exe)
                   _wwine_exe "$_wwine__name" "$@" ;;
               t|tricks)
                   _wwine_tricks "$_wwine__name" "$@" ;;
           esac ;;
    esac
}

wwine()
{
    _wwine "$@"
    wwine="$?"
    [ -n "$_wwine" ] && printf "%s\n" "$_wwine"
    return $wwine
}

wwine_usage()
{
    echo "Usage : wwine [wwine_name] [list|setup|exe|tricks] [command_opts]"
    echo "  wwine list"
    echo "  wwine star_wars list"
    echo "  wwine star_wars setup [arch=win64|win32]"
    echo "  wwine star_wars exe ..."
    echo "  wwine star_wars tricks ..."
}

if [ -n "$DEBUG" ]; then
    set -x
fi

if [ "wwine" = "${0##*/}" ]; then
    while getopts :hD opt; do
        case $opt in
            h) wwine_usage ; exit 0 ;;
            D) set -x ;;
        esac
    done
    wwine "$@"
fi

# wwine list
# wwine star_wars list
# wwine star_wars setup ...
# wwine star_wars exe ...
# wwine star_wars tricks ...

# FIXME : add wineconsole support
#         $ wineconsole cmd
# FIXME : add winetricks support
#         $ winetricks
# DOC   : https://wiki.archlinux.org/index.php/wine#WINEARCH
